name: shrine_images
description: Image assets for the Material Components for Flutter codelabs based on an app called Shrine.
version: 2.0.2
repository: https://github.com/material-components/material-components-flutter-codelabs-packages

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
