name: shrine_images
description: Image assets for the Material Components for Flutter codelabs based on an app called Shrine.
version: 1.1.0
author: Will Larche <larche@google.com>
homepage: https://github.com/material-components/material-components-flutter-codelabs-packages

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=1.19.0 <2.1.0'
  flutter: '>=0.1.0 <2.0.0'